[package]
name = "security_os"
version = "0.1.0"
edition = "2021"


license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
rustls = { version = "0.21", default-features = false }
rustls-pemfile = "1"
x509-parser = "0.16"

