site_name: Ritma
site_url: https://ritma.io/
docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Production Setup: production_setup.md
  - CLI Reference: CLI_REFERENCE.md
  - Forensics Standard: ritma_transparency_forensics.md
  - RTSL Spec: RTSL_SPEC.md
  - EEC Spec: EEC_SPEC.md
