[package]
name = "ritma_lab_node"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ritma-lab-node"
path = "src/main.rs"

[dependencies]
ritma_lab_proto = { path = "../ritma_lab_proto" }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
