apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-utld-ingress
  namespace: ritma-system
spec:
  podSelector:
    matchLabels:
      app: utld
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bar-orchestrator
    ports:
    - protocol: TCP
      port: 8088
