apiVersion: v1
kind: Service
metadata:
  name: utld
  namespace: ritma-system
spec:
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: utld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utld
  namespace: ritma-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utld
  template:
    metadata:
      labels:
        app: utld
    spec:
      containers:
      - name: utld
        image: ritma/utld:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        env:
        - name: NAMESPACE_ID
          value: "ns://k8s/default"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
