[package]
name = "tracer_sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
common_models = { path = "../common_models" }
index_db = { path = "../index_db" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
uuid = { version = "1", features = ["v4"] }
