version: "3.3"
services:
  ritma-demo:
    build:
      context: ..
      dockerfile: docker/Dockerfile-demo
    image: ritma/demo:latest
    container_name: ritma-demo
    environment:
      - NAMESPACE_ID=ns://demo/dev/hello/world
      - INDEX_DB_PATH=/var/lib/ritma/index_db.sqlite
    volumes:
      - ./demo-data:/var/lib/ritma
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
