[package]
name = "biz_api"
version = "0.1.0"
edition = "2021"


license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
core_types = { path = "../core_types" }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
