[package]
name = "trust_hardening"
version = "0.1.0"
edition = "2021"


license = "Apache-2.0"

[dependencies]
index_db = { path = "../index_db" }
common_models = { path = "../common_models" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
sha2 = "0.10"
hex = "0.4"
thiserror = "1"
