[package]
name = "utl_client"
version = "0.1.0"
edition = "2021"


license = "Apache-2.0"

[dependencies]
utld = { path = "../utld" }
utl_core = { path = "../utl_core" }
common_models = { path = "../common_models" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
