[package]
name = "security_host"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
security_os = { path = "../security_os" }
security_events = { path = "../security_events" }
