[package]
name = "utl_cue"
version = "0.1.0"
edition = "2021"


license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
truthscript = { path = "../truthscript" }
tenant_policy = { path = "../tenant_policy" }
