[package]
name = "utl_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
dig_mem = { path = "../dig_mem" }
dig_index = { path = "../dig_index" }
utl_client = { path = "../utl_client" }
utld = { path = "../utld" }
policy_engine = { path = "../policy_engine" }
truthscript = { path = "../truthscript" }
tenant_policy = { path = "../tenant_policy" }
zk_snark = { path = "../zk_snark" }
core_types = { path = "../core_types" }
hmac = "0.12"
sha2 = "0.10"
compliance_model = { path = "../compliance_model" }
compliance_engine = { path = "../compliance_engine" }
security_events = { path = "../security_events" }
compliance_index = { path = "../compliance_index" }
policy_store = { path = "../policy_store" }
reqwest = { version = "0.11", features = ["blocking", "json"] }
compliance_rulepacks = { path = "../compliance_rulepacks" }
evidence_package = { path = "../evidence_package" }
node_keystore = { path = "../node_keystore" }
rusqlite = "0.31"
