[package]
name = "ml_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
common_models = { path = "../common_models" }
security_interfaces = { path = "../security_interfaces" }
uuid = { version = "1", features = ["v4"] }
