[package]
name = "zk_snark"
version = "0.1.0"
edition = "2021"

[dependencies]
core_types = { path = "../core_types" }
ark-ff = "0.5"
ark-ec = "0.5"
ark-groth16 = "0.5"
ark-bn254 = "0.5"
ark-relations = "0.5"
rand = "0.8"
ark-crypto-primitives = "0.5"
hex = "0.4"
