[package]
name = "bar_client"
version = "0.1.0"
edition = "2021"

[dependencies]
bar_core = { path = "../bar_core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"
