[package]
name = "trust_container"
version = "0.1.0"
edition = "2021"


license = "Apache-2.0"

[dependencies]
core_types = { path = "../core_types" }
distillium = { path = "../distillium" }
serde = { version = "1", features = ["derive"] }
